### ISSUE TITLE
status?

### ISSUE THREAD

**Issue by dandlezzz** [ngty/sourcify#34]
Hey all,
I am hoping to use this for a new project. Is it current with ruby 2.2 ? There hasn't been much activity lately?

**Comment by ngty** [comment]
Yup, the project isn't maintained anymore.

**Comment by dandlezzz** [comment]
Is there another alternative, also can we release the edge version to rubyGems. I was hoping to use it for the development of another gem and would prefer not to point to the git repo as a dependency.

**Comment by ngty** [comment]
U can take a look at https://github.com/banister/method_source to see it fits ur need. So the latest for sourcify is a pre-release `0.6.0-rc4`. I'll reluctant to make further releases as that means fixing everything broken for current rubies, which i dont have the resource nor the motivation to handle now.
