### ISSUE TITLE
NoMethodError: undefined method `[]' for nil:NilClass in proc/scanner/dstring.rb:49:in `start_tag'

### ISSUE THREAD

**Issue by joaohornburg** [ngty/sourcify#35]
Running with rails console:
```
Loading development environment (Rails 4.1.5)
>> def la &block
>>   binding.pry
>>   end
=> :la
>> la { p "asd" }
[1] pry(main)> block.to_source
NoMethodError: undefined method `[]' for nil:NilClass
from /usr/local/var/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/sourcify-0.5.0/lib/sourcify/proc/scanner/dstring.rb:49:in `start_tag'
```

**Comment by joaohornburg** [comment]
Using ruby '2.1.5' and 'rails', '4.1.5'

**Comment by ngty** [comment]
Hey @joaohornburg , thank you for reporting the issue .. sourcify was written in the pre ruby-2 days. i'm sorry, this won't be fixed in the short to mid term, as no longer have the resource & interest to work on this project.

**Comment by gerrywastaken** [comment]
Are you able to add a notification about this to the top of the project readme? Otherwise more issues like this are bound to be opened.

**Comment by ngty** [comment]
Agree, lets do it now.

**Comment by gerrywastaken** [comment]
Thank you for adding that. :) I'm sure it will save many a lot of hassle, figuring out what is wrong.
